# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('avatar', models.ImageField(default='avatar/default.png', max_length=200, upload_to='avatar/%m', verbose_name='头像')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='QQ号码')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='电话号码')),
            ],
            options={
                'verbose_name': '用户',
                'ordering': ['-id'],
                'verbose_name_plural': '用户',
            },
        ),
    ]
