# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170823_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='datae_publish',
            new_name='date_publish',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='cataegory_id',
            new_name='catagory_id',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data_publish',
            new_name='date_publish',
        ),
    ]
